### ISSUE TITLE
Texture Loss in the area of Vespucci

### ISSUE THREAD

**Issue by ToasterF16** [TayMcKenzieNZ/MapFixes#2]
![image](https://user-images.githubusercontent.com/70760313/176537072-f2f2ad52-35c2-4d30-a9ef-8fa25eebd02c.png)
![image](https://user-images.githubusercontent.com/70760313/176537085-f897ec94-2947-4001-832f-bd02cd3b8127.png)

This does not occur with the script disabled and has been reported by several players on our server.

**Comment by TayMcKenzieNZ** [comment]
Strange 🤔 Was there a specific area that you were wanting to fix? It could be that you have an MLO or something in that area that is conflicting with some of the files of this resource.

What I'd recommend is, downloading the map fixes separately from 

https://forum.cfx.re/u/luky00010/summary

**Comment by TayMcKenzieNZ** [comment]
Can you please try updating your server artifacts:


Windows: https://runtime.fivem.net/artifacts/fivem/build_server_windows/master/


Linux:

https://runtime.fivem.net/artifacts/fivem/build_proot_linux/master/

**Comment by TayMcKenzieNZ** [comment]
You need to update this at least once a month
