### ISSUE TITLE
[Suggestion] Fix of this hole

### ISSUE THREAD

**Issue by benjatw** [TayMcKenzieNZ/MapFixes#3]
coordinates
-73.9060, -538.8979, 39.2104, 165.6900
![image](https://user-images.githubusercontent.com/30190742/209241132-4ada54e9-5fe6-4017-a89e-a960eba0aa83.png)

**Comment by benjatw** [comment]
565.7291, -586.5521, 43.2113, 248.5796
![image](https://user-images.githubusercontent.com/30190742/209241247-a1ba0bb9-4db7-4fa9-aa9e-b401f75469ec.png)

**Comment by TayMcKenzieNZ** [comment]
Hello,

Thank you for your suggestion; unfortunately I do not know anything about 3D modeling etc.

All map fixes were done by the person I credited. They released all these fixed as individual releases and I just combined them with their permission.
